# Generated by Django 5.1 on 2024-08-12 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('admin', 'Admin')], max_length=10, null=True),
        ),
    ]
